config/routes.rb
Rails.application.routes.draw do
  #resources :sessions
  # home/root can be set with events controller (index)
  resources :users
  resources :events
  root 'events#index'

  put '/event', to: 'events#rsvp'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/event.rb
class Event < ApplicationRecord
    belongs_to :creator, :class_name => "User"
    has_many :event_connections, :foreign_key => :attended_event_id
    has_many :attendees, :through => :event_connections
end

app/models/event_connection.rb
class EventConnection < ApplicationRecord
    belongs_to :attendee, :class_name => "User"
    belongs_to :attended_event, :class_name => "Event"
end

app/models/user.rb
class User < ApplicationRecord
    has_many :created_events, :foreign_key => :creator_id, :class_name => "Event"
    has_many :event_connections, :foreign_key => :attendee_id
    has_many :attended_events, :through => :event_connections
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  helper_method :current_user, :logged_in?

  def log_in(user)
    session[:user_id] = user.id
    current_user
  end

  def current_user=(user)
    user ? user : nil
  end

  def current_user
    @current_user ||= current_user=(User.find_by(id: session[:user_id]))
    return @current_user
  end

  def logged_in?
    !current_user.nil?
  end

  def log_out
    session.delete(:user_id)
    @current_user = nil
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  def index
    @events = Event.all
  end

  def new
    @event = Event.new
  end

  def create
    if logged_in?
      params[:event][:creator_id] = current_user.id
      @event = Event.new(event_params)
      if @event.save
        render 'show'
      end
    else
      flash[:danger] = "You must be logged in for this action."
      redirect_to login_path
    end
  end

  def show
    @event = Event.find(params[:id])
  end

  def update
    @event = Event.find(params[:id])
    if logged_in?
      flash[:success] = "You've been added to the guest list."
      save_rsvp
      render 'show'
    else
      flash[:danger] = "You must be logged in for this action."
      redirect_to login_path
    end
  end


  private

    def event_params
      params.require(:event).permit(:name, :description, :event_date, :creator_id)
      # figure out how to record creator_id
    end

    def save_rsvp
      @event.attendees << current_user
      @event.save
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(id: params[:session][:user_id])
    if user
      log_in(user)
      redirect_to user
    else
      flash[:danger] = "Invalid user."
      render 'new'
      # flash[:danger] = "Invalid user. Please try again."
      # redirect_to root_url
    end
  end

  def destroy
    log_out if logged_in?
    redirect_to root_url
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  helper_method :upcoming_events, :previous_events

  def index
    @users = User.all
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      log_in(@user)
      render 'show'
    end
  end

  def show
    @user = User.find(params[:id])
  end

  def upcoming_events
    @user.attended_events.where("event_date > ?", Time.now)
  end

  def previous_events
    @user.attended_events.where("event_date < ?", Time.now)
  end

  private
    def user_params
      params.require(:user).permit(:name, :email)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/events/index.html.erb
<h1>List of Events</h1>
<ul>
    <% @events.each do |event| %>
        <li><%= link_to event.name, event_path(event.id) %></li>
    <% end %>
</ul>

app/views/events/new.html.erb
<h1>Create a New Event</h1>

<%= form_for @event do |f| %>
    <%= f.label :name %>
    <%= f.text_field :name %><br />

    <%= f.label :event_date %>
    <%= f.datetime_field :event_date %><br />

    <%= f.label :description %>
    <%= f.text_area :description %><br />

    <%= f.submit "Create Event" %>    
<% end %>

app/views/events/show.html.erb
<h1><%= @event.name %></h1>
<p><strong>When:</strong> <%= @event.event_date %></p>
<p><strong>Hosted by:</strong>  <%= link_to @event.creator.name, user_path(@event.creator.id) %></p>

<p><strong>Details:</strong> <%= @event.description %></p>

<strong>Guest list:</strong> 
<% unless @event.attendees.empty? %>
    <ul>
        <% @event.attendees.each do |attendee| %>
            <li><%= link_to attendee.name, user_path(attendee.id) %></li>
        <% end %>
    </ul>
<% else %>
    <p>No one yet.</p>
<% end %>

<% unless @event.attendees.include? current_user %>
    <%= link_to "Click here to join this event.", event_path(@event.id), method: :put %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PrivateEvents</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% flash.each do |key, value| %>
      <%= value %>
    <% end %>
    <% if logged_in? %>
      <h4>Logged in: <%= current_user.name %></h4>
    <% end %>
    <ul class="header">
      <li><%= link_to "Home", root_url %></li>
      <% if !logged_in? %>
        <li><%= link_to "Login", login_path %></li>
        <li><%= link_to "Sign up", new_user_path %></li>
      <% else %>
        <li><%= link_to "Profile", user_path(current_user.id) %></li>
        <li><%= link_to "Create A New Event", new_event_path %></li>
        <li><%= link_to "Logout", logout_path, method: :delete %></li>
        <li><%= link_to "User List", users_path %></li>
      <% end %>
    </ul>

    <%= yield %>
  </body>
</html>

app/views/users/index.html.erb
<h1>List of Users</h1>

<ul>
    <% @users.each do |user| %>
        <li><%= link_to user.name, user_path(user.id) %></li>
    <% end %>
</ul>

app/views/users/new.html.erb
<h1>Sign up</h1>
<%= form_for @user do |f| %>
    <%= f.label :name %>
    <%= f.text_field :name %><br />

    <%= f.label :email %>
    <%= f.email_field :email %><br />

    <%= f.submit "Sign up" %>
<% end %>

app/views/users/show.html.erb
<h1><%= @user.name %></h1>
<p>Here's your profile, I guess.</p>
<h4>Events that I'm hosting:</h4>
<% unless @user.created_events.empty? %>
    <ul>
        <% @user.created_events.each do |event| %>
            <li><%= link_to event.name, event_path(event.id) %></li>
        <% end %>
    </ul>
<% else %>
    <p>No events found</p>
<% end %>
<br />
<% unless @user.attended_events.empty? %>
    <h4>Events that I'm attending:</h4>
    <ul>
        <% upcoming_events.each do |event| %>
            <li><%= link_to event.name, event_path(event.id) %></li>
        <% end %>
        <% if upcoming_events.empty? %>
            <p>Doesn't look like anything to me.</p>
        <% end %>
    </ul>
    <h4>Events that I already attended:</h4>
    <ul>
        <% previous_events.each do |event| %>
            <li><%= link_to event.name, event_path(event.id) %></li>
        <% end %>
        <% if previous_events.empty? %>
            <p>Doesn't look like anything to me.</p>
        <% end %>
    </ul>
<% else %>
    <p>None yet</i>
<% end %>